#
# Build
#
FROM maven:3.9.6 AS build
COPY src /proj.gardenstore/src
COPY pom.xml /proj.gardenstore
RUN mvn -B -f /proj.gardenstore/pom.xml clean package
#
# Package stage
#
FROM nginx:latest
COPY --from=build /proj.gardenstore/target/projetjavafinal-1.0-SNAPSHOT.jar /usr/local/lib/projetjavafinal.jar
ENTRYPOINT ["java","-jar","/usr/local/lib/projetjavafinal.jar"]