spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/gardenstore_db
    username: cédric
    password: simcity1985
    driver-classname: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-circular-references: true

server:
  port: 8080
