spring:
  datasource:
    url: jdbc:postgresql://8000:5432/gardenstore_db
    username: cedric
    password: simplicity1985
    driver-classname: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-circular-references: true

server:
  port: 8080
